"""audit logs table and four role enum

Revision ID: 65aa92692aa1
Revises: 0e1f15f65199
Create Date: 2026-08-24 18:52:47.646195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65aa92692aa1'
down_revision: Union[str, Sequence[str], None] = '0e1f15f65199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: Alembic does not autodetect enum value additions (ADR-007).
    # PostgreSQL 12+ permits ALTER TYPE ... ADD VALUE inside transactional DDL
    # as long as the new values are not used within the same transaction.
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'COMMITTEE'")
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'ACCOUNTANT'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # NOTE: PostgreSQL cannot remove enum values. COMMITTEE/ACCOUNTANT remain
    # in user_role after downgrade; they are simply no longer assigned.
    # ### end Alembic commands ###
