"""invoice unique resident plan period

Revision ID: 1fcaffd1a5ef
Revises: a468819ad4a6
Create Date: 2026-08-24 19:09:01.990464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcaffd1a5ef'
down_revision: Union[str, Sequence[str], None] = 'a468819ad4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_invoice_resident_plan_period', 'invoices', ['resident_id', 'plan_id', 'billing_period'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoice_resident_plan_period', 'invoices', type_='unique')
    # ### end Alembic commands ###
