"""accounting expenses funds

Revision ID: 719171787bc9
Revises: 190491979896
Create Date: 2026-08-24 19:31:08.197735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719171787bc9'
down_revision: Union[str, Sequence[str], None] = '190491979896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recurring_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('ELECTRICITY', 'WATER', 'SECURITY', 'REPAIRS', 'CLEANING', 'SALARIES', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUAL', name='expense_frequency'), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('next_run_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('last_generated_period', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('ELECTRICITY', 'WATER', 'SECURITY', 'REPAIRS', 'CLEANING', 'SALARIES', 'OTHER', name='expense_category'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('receipt_file_path', sa.String(length=500), nullable=True),
    sa.Column('source_recurring_id', sa.UUID(), nullable=True),
    sa.Column('generated_period', sa.String(length=7), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_recurring_id'], ['recurring_expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_table('fund_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='fund_transaction_type'), nullable=False),
    sa.Column('source', sa.Enum('MAINTENANCE_PAYMENT', 'EXPENSE', 'MANUAL_CREDIT', 'MANUAL_DEBIT', 'ADJUSTMENT', name='fund_transaction_source'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['maintenance_funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_transactions_fund_id'), 'fund_transactions', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_transactions_fund_id'), table_name='fund_transactions')
    op.drop_table('fund_transactions')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('recurring_expenses')
    op.drop_table('maintenance_funds')
    # ### end Alembic commands ###
